### ISSUE TITLE
"yarn add iitcpluginkit" doesn't work

### ISSUE THREAD

**Issue by cobra7476** [McBen/IITCPluginKit_Example#12]
hello,

**Comment by cobra7476** [comment]
I have installed yarn and node JS, and when I do "yarn add iitcpluginkit", the response is :
`$ yarn add iitcpluginkit
➤ YN0000: ┌ Resolution step
➤ YN0001: │ RequestError: 33428:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:677:

at ClientRequest.<anonymous> (C:\Users\admin\Documents\dev\github\cobra7476\1stPluginIITCCE\.yarn\releases\yarn-sources.cjs:144:14356)
at Object.onceWrapper (node:events:628:26)
at ClientRequest.emit (node:events:525:35)
at ClientRequest.c.emit (C:\Users\admin\Documents\dev\github\cobra7476\1stPluginIITCCE\.yarn\releases\yarn-sources.cjs:139:14420)
at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._emitTLSError (node:_tls_wrap:905:10)
    at TLSWrap.onerror (node:_tls_wrap:436:11)
➤ YN0000: └ Completed in 4s 11ms
➤ YN0000: Failed with errors in 4s 14ms
➤ YN0061: stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility`


do you know what is the problem?

**Comment by cobra7476** [comment]
sorry, I don't hunderstand, but finaly, this command work on an other directory

edit : I have done yarn init-2 in the same file to the yarn add iitcpluginkit, and probably this is the cause of the error
